config/routes.rb
Trainingproject::Application.routes.draw do
  root :to => 'shorts#new'
  resources :shorts, :only => [:new, :create, :show]
end

app/models/short.rb
class Short < ActiveRecord::Base
  attr_accessible :long, :desc
  attr_accessor :desc

  validates :long,
  				:presence => true,
  				:format => {
  							:with => %r{^http://},
  							:message => "Only HTTP links are allowed!"
  				}
  	def to_param
  		if self.desc.nil?
  			b36_id
  		else
  			"#{b36_id}/#{self.desc}"
  		end
  	end

  	def b36_id
  		self.id.to_i.to_s(36)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController

	def show
		@short = Short.find(params[:id].to_i(36))

		respond_to do |format|
			#redirect directly to the url stored as long in the database
			format.html { redirect_to @short.long}
		end
	end

	def new
		@short = Short.new

		respond_to do |format|
			format.html # new.html.erb
		end
	end

	def create
		@short = Short.new(params[:short])

		respond_to do |format|
			if @short.save

				format.html { render action: "show" }

			else

				format.html { render action: "new" }
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_helper.rb
module ShortHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trainingproject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "short", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shorts/_form.html.erb
<%= form_for @short, :html => {:class => "extra-form-styling"} do |f| %>
	<% if @short.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@short.errors.count,"error") %> prohibited this url from being saved:</h2>
			<ul>
				<% @short.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

		
			<%= f.text_field :long, :placeholder => "Paste your url", :class =>'form-field' %>
			<%= f.text_field :desc, :placeholder => "Optional Description", :class => 'form-field' %>
		<div class="actions">
			<%= f.submit "Make it short", :class => 'create-button' %>
		</div>
<% end %>

app/views/shorts/_short.html.erb
<center>
	<div class = "result">
	
		<p>Cool, now you can share this with your friends!</p>
		<%= link_to short_url(@short), short_url(@short) %>
	</div>

	<div id="link-for-more">
		<%= link_to 'Make another link', new_short_path %> 
	</div>
</center>

app/views/shorts/create.html.erb
create pagina

app/views/shorts/create.js.erb
$(".result-<%=@short>").append("<%= escape_javascript"(render :partial => 'shorts/_short', :locals => {:comment => @comment})%>");

app/views/shorts/new.html.erb
<div id="the-form">
	<center> <%= render 'form' %> </center>
</div>

app/views/shorts/show.html.erb
<center>
	<div class = "result">
	
		<p>Cool, now you can share this with your friends!</p>
		<%= link_to short_url(@short), short_url(@short) %>
	</div>

	<div id="link-for-more">
		<%= link_to 'Make another link', new_short_path %> 
	</div>
</center>

app/views/shorts/welcome.html.erb
<p><%= link_to 'Welcome, make a link', new_short_path %></p>